### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by pyros2097** [fouber/cluster-daemon#1]
Since it is in Chinese I can't understand what this does? Is it possible for an English translation?

**Comment by fouber** [comment]
Not long ago, our application had memory leak problem for some reasons we did't know, so I wrote this to monitor if there is leaking memory on workers, and it will kill the worker when it leaks memory after processing http response, so that master can hold on with other workers.

But after a few tests, I found it DOES NOT work well, there must be something wrong! 

So, forget this, keep away from nodejs, you will enjoy a long life.

**Comment by pyros2097** [comment]
Is nodejs that bad? What about iojs? It has many impovements. But nowdays people are all using golang.
